version: "3"
services:
  proxy:
    image: fugroup/proxy:latest
    ports:
      - 8888:8080
    networks:
      - external
    depends_on:
      - websocket
      - account
      - upload
  setup:
    image: bitnami/mongodb:latest
    user: root
    command: chown -R 1001:1001 /bitnami
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - data:/bitnami
    networks:
      - internal
    depends_on:
      - setup
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - internal
    depends_on:
      - mongodb
  websocket:
    image: fugroup/websocket:latest
    restart: always
    ports:
      - 5555:5555
    environment:
      - NODE_ENV=production
    networks:
      - external
      - internal
    depends_on:
      - mongodb
      - redis
  account:
    image: fugroup/account:latest
    restart: always
    ports:
      - 6666:6666
    environment:
      - NODE_ENV=production
    networks:
      - external
      - internal
    depends_on:
      - mongodb
      - redis
  upload:
    image: fugroup/upload:latest
    restart: always
    ports:
      - 7777:7777
    environment:
      - NODE_ENV=production
    networks:
      - external
      - internal
    depends_on:
      - mongodb
      - redis
networks:
  external:
  internal:
volumes:
  data:
    driver: local
